### ISSUE TITLE
mutli words search

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/recherche-entreprises#112]
quand on cherche "risser informatique" il arrive en 3eme position (branche sqlite)

**Comment by rmelisson** [comment]
il arrive en 3eme position à cause du ranking par taille d'établissement, c'est pas par rapport à l'upper case

**Comment by rmelisson** [comment]
lié à #73 je vais rajouter un champs pour utiliser ou non le tri effectif

**Comment by revolunet** [comment]
fixed thanks
