### ISSUE TITLE
Ajouter le code INSEE de l'adresse du siège social de l'entreprise

### ISSUE THREAD

**Issue by pom421** [SocialGouv/recherche-entreprises#128]
Bonjour, 

Une info qui nous serait utile, serait d'avoir en plus de l'adresse, le code INSEE de l'adresse de l'entreprise. 

Par exemple, voici ce que rend l'API entreprise dans la partie adresse : 

`"adresse": {
      "l1": "MCDONALD'S FRANCE",
      "l2": null,
      "l3": "Z I",
      "l4": "1 RUE GUSTAVE EIFFEL",
      "l5": null,
      "l6": "78045 GUYANCOURT CEDEX",
      "l7": "FRANCE",
      "numero_voie": "1",
      "type_voie": "RUE",
      "nom_voie": "GUSTAVE EIFFEL",
      "complement_adresse": "Z I",
      "code_postal": "78280",
      "localite": "GUYANCOURT",
      "code_insee_localite": "78297",
      "cedex": "78045"
    },`

Le `code_insee_localite` est capital puisqu'il permet ensuite de déduire le département/collectivité d'outre mer.
Le code postal seul, ne suffit pas à faire cette déduction (référence : https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_dont_le_code_postal_ne_correspond_pas_au_d%C3%A9partement).

**Comment by rmelisson** [comment]
le code insee c'est bien le code commune qu'on a ajouté sur l'autre issue ?

**Comment by revolunet** [comment]
toujours d'actu @pom421  ?

**Comment by pom421** [comment]
Je viens de tester sur quelques exemples, ça a l'air bon : le `codeCommuneEtablissement` de l'API Recherche entreprises est bien équivalent au `code_insee_localite` de l'API Entreprises.
