### ISSUE TITLE
Ajouter l'adresse du siège social

### ISSUE THREAD

**Issue by pom421** [SocialGouv/recherche-entreprises#129]
Re! 

J'ai l'impression que l'on n'a pas l'adresse du siège social de l'entreprise, mais uniquement les adresses des établissements. 

Ça nous serait très utile pour afficher une adresse unique à l'affichage.

**Comment by pom421** [comment]
Je complète ma demande : 

Par exemple, pour le endpoint entreprise et le SIREN de MacDonald's: 
https://search-recherche-entreprises.fabrique.social.gouv.fr/api/v1/entreprise/722003936

On a dans ce cas un champ `firstMatchingEtablissement` qui ne contient pas les données du siège, donc je ne comprends pas à quoi correspond ce premier établissement qui matche? 
Cet objet contient une propriété `codeCommuneEtablissement` qui est très pratique, car elle rend le code INSEE de la commune, ce qui nous permet de savoir le département ou l'identifiant du territoire d'outre mer. Malheureusement, ce champ n'est pas reproduit pour tous les établissements, seulement pour ce `firstMatchingEtablissement`. 

Donc ma demande, serait d'ajouter `codeCommuneEtablissement` pour tous les établissements. 

D'autre part, il nous rend dans ce cas 1391 établissements, ce qui fait un retour assez énorme (33 kB) pas utile dans une utilisation interactive et dispendieuse pour l'API.

Donc ma demande serait de pouvoir paramétrer la granularité du retour de ce endpoint. 
Un exemple serait d'avoir un champ dans la requête de l'API, pour rendre par défaut uniquement les infos du SIREN (dont le siège social) ou bien rendre si besoin tous les établissements? Par exemple un champ `etablissementsMode`, soit égal à "tous", soit égal à "siège social", cette valeur étant la valeur par défaut.

**Comment by rmelisson** [comment]
hello,
- concernant le nombre d'établissements retournés, je pensais effectivement le restreindre via un paramètre de l'API
- le `firstMatchingEtablissement` est l'établissement qui correspond le mieux à la recherche textuelle (dans le cas du nom specifique d'un établissement par exemple), c'était notre premier use case (recherche d'établissement par nom)
- ok pour ajouter le `codeCommuneEtablissement` aux autres établissements, tu voulais le code NAF aussi, c'est bien ça ?
- enfin pour le siège social, c'est quelque chose que nous n'avons pas regardé, dans le cas du endpoint `entreprise/:siret` il serait effectivement assez logique que le `firstMatchingEtablissement` soit le siège social, il faut que je regarde comment l'identifier

**Comment by pom421** [comment]
Thanks !
Oui, on aurait besoin du code NAF pour Egapro. 

Si ça a du sens, tu peux laisser `firstMatchingEtablissement` et créer une nouvelle propriété supplémentaire pour un objet pour le siège social.

**Comment by rmelisson** [comment]
yes bonne idée, j'ai trouvé le champs pour identifier le siege social
