### ISSUE TITLE
Ajouter la date de cessation d'une entreprise

### ISSUE THREAD

**Issue by pom421** [SocialGouv/recherche-entreprises#162]
Bonjour, 

Pour Egapro, il nous serait utile d'avoir la date de fin à laquelle une entreprise a cessé son activité. 
Côté API Entreprise, ce champ s'appelle `date_cessation` donc pour respecter le nommage des champs ce pourrait être `dateCessation`. 

Si ça ne vous coûte pas, on pourrait ajouter également un champ `dateCreation`.

**Comment by pom421** [comment]
Peut être un doublon de #158 ?

**Comment by pom421** [comment]
@revolunet toujours intéressé pour Egapro ^^

**Comment by pom421** [comment]
Note : pour Egapro, on choisit plutôt date de cessation plutôt que date de radiation, pour déduire qu'une entreprise est fermée.

**Comment by revolunet** [comment]
ajout du champ `dateDebut` dans l'API
