### ISSUE TITLE
SIREN introuvables

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/recherche-entreprises#198]
Lors de tests sur l'application `Egapro`, une partie des SIREN utilisés ne remonte pas de résultat.

En partant du principe que l'URL de l'API, décrite [dans le Swagger](https://api.recherche-entreprises.fabrique.social.gouv.fr/#/Recherche/siren) et permettant d'effectuer une recherche par SIREN est bien:

```
https://api.recherche-entreprises.fabrique.social.gouv.fr/api/v1/entreprise/<SIREN>
```

Voici la liste des SIREN incriminés:
- 504451139:
    - [API](https://api.recherche-entreprises.fabrique.social.gouv.fr/api/v1/entreprise/504451139)
    - [Annuaire Entreprise](https://annuaire-entreprises.data.gouv.fr/entreprise/504451139)
- 512449539:
    - [API](https://api.recherche-entreprises.fabrique.social.gouv.fr/api/v1/entreprise/512449539)
    - [Annuaire Entreprise](https://annuaire-entreprises.data.gouv.fr/entreprise/512449539)
- 879538858:
    - [API](https://api.recherche-entreprises.fabrique.social.gouv.fr/api/v1/entreprise/879538858)
    - [Annuaire Entreprise](https://annuaire-entreprises.data.gouv.fr/entreprise/879538858)
- 501636534:
    - [API](https://api.recherche-entreprises.fabrique.social.gouv.fr/api/v1/entreprise/501636534)
    - [Annuaire Entreprise](https://annuaire-entreprises.data.gouv.fr/entreprise/501636534)
- 453739112:
    - [API](https://api.recherche-entreprises.fabrique.social.gouv.fr/api/v1/entreprise/453739112)
    - [Annuaire Entreprise](https://annuaire-entreprises.data.gouv.fr/entreprise/453739112)
- 440305282:
    - [API](https://api.recherche-entreprises.fabrique.social.gouv.fr/api/v1/entreprise/440305282)
    - [Annuaire Entreprise](https://annuaire-entreprises.data.gouv.fr/entreprise/440305282)
- 530588102:
    - [API](https://api.recherche-entreprises.fabrique.social.gouv.fr/api/v1/entreprise/530588102)
    - [Annuaire Entreprise](https://annuaire-entreprises.data.gouv.fr/entreprise/530588102)

**Comment by revolunet** [comment]
Il semblerait que les dernières livraison des fichiers geo_siret que nous utilisons ont été amputées de pas mal de données.... du coup on a plus que 8M d'établissements au lieu de 32 :/

 - [Livraison 09/22](https://files.data.gouv.fr/geo-sirene/2022-09/dep/) : 
 - [Livraison 10/22](https://files.data.gouv.fr/geo-sirene/2022-10/dep/) : 
 
 Je vais restaurer l'index précédent et remonter le "problème" à data.gouv

**Comment by revolunet** [comment]
![done](https://media.giphy.com/media/fOzVB89gnznJXaZ1Ti/giphy.gif)

33263520 établissements

**Comment by revolunet** [comment]
Donc l'INSEE aurait publié un mauvais fichier au 1/10, les fichiers corrigés arrivent d'ici demain, je relancerai l'indexation à ce moment là

**Comment by revolunet** [comment]
la dernière version a été indéxée
