### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/recherche-entreprises#36]
Ex: "café paris" VS "cafe paris"

**Comment by rmelisson** [comment]
En fait c'est ok mais il reste un corner case avec le fuzzy search.
Dans ton cas, c'est flagrant car ta requête match beaucoup de résultats.
Essaye le même exemple mais à Noirmoutier, normalement ça passe (et ça donne envie d'aller y faire un tour :) )

J'ai quand même fix un prob lié à ça.
