### ISSUE TITLE
Tri et entreprises sans salariés

### ISSUE THREAD

**Issue by mquandalle** [SocialGouv/recherche-entreprises#73]
Salut,

L'API entreprise que l'on utilise sur mon-entreprise.fr ne fonctionne plus du tout, il faut que l'on migre rapidement sur votre API. https://github.com/betagouv/mon-entreprise/issues/1631 Le cas d'usage est légèrement différent de celui sur code-du-travail-numérique et il faut que l'on puisse :

- référencer les entreprises individuelles (auto-entrepreneurs et entreprises sans salariés)
- ne pas afficher les plus grosses entreprises en premier

Pouvez-vous nous aider à ajouter ces paramètres ?

**Comment by lionelB** [comment]
Hello

Est ce que tu aurais des ex pour les entreprises individuelles (auto-entrepreneurs et entreprises sans salariés) pour voir a quel niveau ça coince dans le process

> ne pas afficher les plus grosses entreprises en premier
on peut rajouter un parametre dans la recherche et dans un second temps je pense qu'on fera peut etre un deuxieme endpoint plus spécifique pour le cdtn ?

poke @revolunet @rmelisson

**Comment by mquandalle** [comment]
> Est ce que tu aurais des ex pour les entreprises individuelles (auto-entrepreneurs et entreprises sans salariés) pour voir a quel niveau ça coince dans le process

Pour les auto-entrepreneurs, le nom de l'entreprise est le même que le prénom + nom de la personne, par exemple “Johan Girod” https://entreprise.data.gouv.fr/api/sirene/v1/full_text/johan%20girod?per_page=5

**Comment by rmelisson** [comment]
hello, désolé j'avais loupé l'issue, il faudrait essayer en indexant les entreprises sans salariés: 
https://github.com/SocialGouv/recherche-entreprises/blob/master/assembly/src/assemble_data.py#L55

il faudra également ajouter un paramètre dans la recherche pour pouvoir filter sur les entreprises sans salarié pour les requêtes CDTN, je passe qqs jours sur le projet semaine prochaine, je pourrai jeter un oeil

**Comment by lionelB** [comment]
Je profite de ton commentaire rémi pour faire un retours suite a une petite investigation, on a bien johan girod dans les données mais on n'indexe pas le prénom du coup il remonte pas bien. (cf #80)

**Comment by bobylito** [comment]
Salut,

Je suis en train de travailler sur cette issue et je crois que le filtre qui est fait sur la base SIRENE est trop "filtrant" 😅

En effet, on trouve dans le [code d'assemblage](https://github.com/SocialGouv/recherche-entreprises/blob/master/assembly/src/assemble_data.py#L55), un filtre sur la colonne `caractereEmployeurUniteLegale` à `O`. Hors d'une part, nous souhaitons pouvoir chercher des entreprises individuelles qui n'emploient personne (à `N` donc) et d'autre part, l'entreprise a pu être employeuse durant l'année mais avoir 0 effectifs au 31/12 (non employeuse -> `N` et `00` dans trancheEffectifUniteLegale).

Je voudrais faire les modifications suivantes:
 - suppression du filtre lors de l'import
 - ajout d'une colonne `uniteEmployeuse` qui sera importé dans ES
 - création d'un aggregat avec cette nouvelle colonne 
 - ajout d'un paramètre dans l'API pour cherche aussi dans les entreprises qui n'emploient pas

Qu'est ce que vous en dites?

Source: [Description des variables du fichier StockUniteLegale](https://www.data.gouv.fr/fr/datasets/r/48e55481-82cf-4d90-9db0-49612e15c36c)

**Comment by revolunet** [comment]
Sounds good to me !

**Comment by mquandalle** [comment]
Autre question, sur un site privé comme https://www.societe.com, on peut rechercher une entreprise à partir du nom du dirigeant. C'est particulièrement utlie pour les petites entreprises. Est-ce envisageable d'indexer cette information ?

**Comment by revolunet** [comment]
La recherche par dirigeant est hors-scope pour l'instant car je ne crois pas que l'on aie cette info dans les datasets utilisés. sais-tu où on peut récupérer l'info @mquandalle  ?
