### ISSUE TITLE
fix api unit tests

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/recherche-entreprises#74]
tests are broken on master

**Comment by rmelisson** [comment]
On utilise maintenant l'index de prod lors des test via les github actions.
À l'avenir, il faudra donc mettre à jour les snapshots lorsque l'on met à jour l'index (action manuelle pour le moment)
À voir si l'on peut basculer sur l'index de dev, mais pour le moment je ne parviens pas à y accéder.
