### ISSUE TITLE
Améliorer la recherche d'entreprises

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/recherche-entreprises#79]
### Description
Dans le parcours "je ne connais pas ma CC" de l'outil "trouver sa CC" actuellement si on recherche Monoprix avec le code postal 75015, le seul résultat est le monoprix 19 rue Linois or il existe d'autres monoprix dans le 75015 : monoprix rue de la convention,  rue Lecourbe... => C'est un exemple parmi d'autres cas.

Un utilisateur nous a également indiqué qu'il ne trouvait pas son entreprise via son siret : 89929385600014 => on trouve bien l'entreprise ici https://annuaire-entreprises.data.gouv.fr/etablissement/89929385600014
Autre siret identifié ne fonctionnnant pas : 49279130600037

Voir si les autres problèmes précédents identifiés sont résolus : 
- Les siret commençant par 0 ne fonctionnent pas (exemple 06980513300076)
- Problème concernant la recherche de conventions collectives :  Idcc avec 0 devant ne fonctionnent pas (exemple 0029)

### Reproduction
**1**
Etapes à suivre pour reproduire le problème
1. Go to 'Trouver sa CC'
2. Click on 'Je ne connais pas ma convention collective'
3. Type 'Monoprix' in the box "Nom de votre entreprise ou numéro Siret (obligatoire)"
4. Type '75015' in the box "Code postal ou ville"

**2**
Etapes à suivre pour reproduire le problème
1. Go to 'Trouver sa CC'
2. Click on 'Je ne connais pas ma convention collective'
3. Type '89929385600014' in the box "Nom de votre entreprise ou numéro Siret (obligatoire)"

**Comment by romain-b13** [comment]
Autre exemple : lorsque l'on tape "Zara" dans le champ entreprise et le code postal 75001 il ne trouve aucun Zara (il existe 2 Zara dans le 75001) : 
![image](https://user-images.githubusercontent.com/84397271/128026852-6b9ab5b8-5cde-41b4-878a-fe2e9c97a594.png)

**Comment by romain-b13** [comment]
Autre exemple : 
lorsque l'on tape "Bricorama" dans le champ entreprise et le code postal 75015 il ne trouve aucun résultat (il existe a priori 1 Bricorama  Zara dans le 75001), de même lorsque l'on essaye avec le code postale 92100

**Comment by rmelisson** [comment]
Hello, j'ai mis à jour l'index ce qui résoud une partie des problèmes.

Voici mes retours sur chacun des cas :

1. Monoprix avec le code postal 75015 : le choix d'UX était de ne retourner qu'un seul établissement pour éviter de surcharger les résultats. Les autres établissements que tu cites sont bien dans l'index mais ne sont pas affichés.

2. siret : 89929385600014  : ces établissements ne disposent pas de convention collective :
https://annuaire-entreprises.data.gouv.fr/divers/899293856

3. siret : 49279130600037 : la mise à jour de l'index a résolu le prob, l'entreprise est désormais bien visibile

4. siret commencant par '0' 06980513300076 : problème résolu également

5. Zara 75001 : zara rue du pont neuf est maintenant visible, pour le second, il ne dispose pas de convention collective (et quand bien même, nous serions dans le même cas qu'en `1.`)

6. Bricorama 75015 : il n'y a pas d'établissement ouvert pour le code postal 75015, par contre tu peux trouver l'établissement de Suresnes (92150), la liste et l'état des établissement ici :
https://annuaire-entreprises.data.gouv.fr/entreprise/406680314

En bref, les fix de Lionel + la mise à jour de l'index semblent avoir résolu la plupart des soucis.
Reste à décider si l'on souhaite changer le comportement décrit en `1.`
Aussi, on voit bien ici le besoin de rafraichissement régulier de la donnée, voir ticket #84

**Comment by rmelisson** [comment]
J'ai oublié la question des idcc qui commencent par `0`, je regarde ça
