### ISSUE TITLE
Mettre à jour régulièrement les données

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/recherche-entreprises#84]
Les informations sur les entreprises changement régulièrement et elles ne sont pas disponible dans l'API.

Idée: Mise en place d'un job github qui tourne à interval régulier.

**Comment by rmelisson** [comment]
on a écrit les scripts de maj (telechargement des datasets / assemblage / création de l'index...) et ça fonctionne mais le soucis c'est que le job est super gourmand en ressources et il plante sur notre CI.
Donc actuellement il faut mettre à jour à la mano... c'est ce que je viens de faire mais il faudrait résoudre les probs côté CI pour automatiser le refresh

**Comment by m-maillot** [comment]
Il y a deux parties actuellement que l'on gère:
1. la récupération du ficheir `WEEZ` contenant les données
2. l'ingestion des données pour mettre à jour l'index elastic alimentant le moteur

### récupération du ficheir `WEEZ` contenant les données

La récupération du fichier est actuellement manuelle. Le fichier `WEEZ` est mis à disposition sur un dossier partagé accessible seulement sur le réseau du ministère. @revolunet le récupère à la main et le pousse sur data.gouv.

### l'ingestion des données pour mettre à jour l'index elastic alimentant le moteur

Le job va récupérer les données sur data.gouv et met à jour l'index. Celui ci est lancé manuellement par @revolunet à chaque mise à jour du fichier.
Cette partie peut être scheduler facilement.

### Conclusion

La première partie nous bloque l'automatisation de la mise à jour des données. Il faut que les données soit directement mise sur data.gouv par le service concerné pour automatiser le processus sinon on ne peut rien faire.

J'ai demandé à Catherine pour faire une demande / relance auprès du service concerné.

**Comment by revolunet** [comment]
La mise à jour de l'index de prod est programmée toutes les semaines : https://github.com/SocialGouv/recherche-entreprises/blob/master/.github/workflows/indexing-prod.yml#L6

cela récupère les dernieres versions des jeux de données sur datagouv
