### ISSUE TITLE
SIREN absent

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/recherche-entreprises#89]
je ne trouve pas cette entreprise `822766358` / `82276635800029` en appelant l'API directement

https://api-recherche-entreprises.fabrique.social.gouv.fr/api/v1/search?q=82276635800029

**Comment by revolunet** [comment]
NB: il n'est pas présent dans le fichier weer

**Comment by rmelisson** [comment]
ça me semble ok maintenant, pê lié à la mise à jour de l'index

https://api-recherche-entreprises-sqlite.dev.fabrique.social.gouv.fr/api/v1/search?query=82276635800029

https://api-recherche-entreprises-sqlite.dev.fabrique.social.gouv.fr/api/v1/etablissement/82276635800029
