### ISSUE TITLE
Ne pas afficher d'adresse quand plusieurs établissements pour un CP

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/recherche-entreprises#90]
**Contexte**
Dans l'outil "trouver sa convention collective" lorsque l'on tape par ex Monoprix et 75015 un seul établissement est affiché alors qu'il en existe bien plusieurs dans le 75015 (un choix d'UX avait été fait de ne retourner qu'un seul établissement pour éviter de surcharger les résultats).

**Solution**
Afficher tous les établissements présents dans le département lorsqu'un code postal est saisi

**Comment by romain-b13** [comment]
MAJ : Afin de rester dans la logique d'éviter la surcharge de résultat et en même temps de ne pas laisser croire à l'utilisateur qu'il ne trouve pas l'établissement qu'il recherche nous faisons le choix suivant : 

**lorsqu'il y a plusieurs établissements dans un même département**, au lieu de n'afficher qu'un seul des établissements (et donc une seule adresse) il faudrait **afficher uniquement le code postal avec la ville** et non pas l'adresse précise d'un des établissements.

Ex : si on fait la rechercher "Monoprix" + "75015" aujourd'hui nous obtenons le résultat suivant : 

![image](https://user-images.githubusercontent.com/84397271/142246803-c1f38f3a-f613-4c29-b081-fc6058037e35.png)

Dans ce cas l'idée serait d'afficher uniquement **"75015 Paris"**

**Seule question restante** : comment cela se passe si un établissement (ex : monop rue linois) du 75015 est rattaché à une seule convention collective (ex : "Commerce de détail et de gros à prédominance alimentaire") alors qu'un autre établissement (ex : monop rue de la convention) du 75015 est rattaché à 2 conventions collectives (ex : "Commerce de détail et de gros à prédominance alimentaire" + "Grands magasins et magasins populaires") 
=> l'utilisateur qui travaille au monop rue linois va quand même obtenir 2 résultats (2 CCs différentes) et va devoir "faire un choix" alors que dans les fait son établissement n'est rattaché qu'à une seule CC

Est-ce que c'est déjà le cas actuellement ? étant donné qu'on affiche qu'1 établissement

**Comment by rmelisson** [comment]
pour le dernier point, voir avec #50

**Comment by rmelisson** [comment]
https://code-du-travail-numerique-remi-cc-search-n-re-1qcnlr.dev.fabrique.social.gouv.fr/

**Comment by rmelisson** [comment]
par contre le nombre de résultats est pas ok, mais c'est par rapport à la recherche, c'est fix sur la nouvelle version
